spring:
  application:
    name: zipjung-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zipjung?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: redis-15066.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com:15066
      port: 15066

server:
  port: 8080

# JWT
jwt:
  secret: ENC(47BYm0Bi79/0rn5GMVgq5m1jBLQmoaHNvNsukvixC/POlFGjDuxebV5c2x1zaAR81ndxbTfxaBM=)

# log
logging:
  level:
    org:
      springframework: info

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}